package main

var gamePhase = map[int]Phase{
	1: {Description: "Chaque joueur choisit secrètement une carte Trait de leur	main et la pose face cachée sur le plateau Point d’eau. Ce sont maintenant des cartes Nourriture végétale qui seront révélées durant la phase d’alimentation pour déterminer la quantité de nourriture végétale qui sera disponible à cette phase (le nombre de jetons Nourriture).", IsSequential: false, Name: "Sélectionner la nourriture"},
	2: {Description: "Chaque joueur peut jouer autant de cartes Trait qu’il le souhaite ou les garder pour un tour suivant. Un joueur peut réaliser 1 action parmi 3 différentes pour chaque carte qu’il joue durant son tour: jouer un trait, créer une nouvelle espèce ou augmenter la taille ou la population d'une de ses espèces.", IsSequential: false, Name: "Jouer les cartes"},
	3: {Description: "Les cartes Nourriture posées sur le plateau Point d’eau sont révélées. La valeur nourriture de ces cartes est aditionnée et autant de jetons Nourriture sont placés sur le plateau Point d’eau. Si le total des cartes Nourriture est négatif, il enlève autant de jetons déjà présents sur le plateau Point d’eau (si possible).", IsSequential: false, Name: "Révéler les cartes"},
	4: {Description: "Chaque carte ayant un effet prioritaire (symbole feuille) est activée.", IsSequential: false, Name: "Activer les cartes prioritaires"},
	5: {Description: "En commençant par le 1er joueur et en continuant dans le sens horaire, chaque joueur doit nourrir une de ses espèces affamées. Une espèce est affamée si elle a moins de jetons Nourriture que de Population. Quand une espèce prend de la nourriture, les jetons sont placés sur la zone prévue à cet effet au-dessus de la piste de Population en commençant par le 1er emplacement libre. Chaque jeton Nourriture rapportera un point en fin de partie.", IsSequential: true, Name: "Nourrir les espèces"},
}
